//! Vellum's price-time priority limit order book.
//!
//! Design notes:
//! - Bids are kept highest-price-first, asks lowest-price-first.
//! - Within a price level, orders are FIFO (first in, first matched) —
//!   this is "time priority".
//! - A `HashMap<order_id, location>` gives O(1) lookup for cancels, since
//!   in real markets cancels vastly outnumber fills.

use protocol::Side;
use std::cmp::Reverse;
use std::collections::{BTreeMap, HashMap, VecDeque};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RestingOrder {
    pub order_id: u64,
    pub qty: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Trade {
    pub resting_order_id: u64,
    pub incoming_order_id: u64,
    pub price: u64,
    pub qty: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct OrderLocation {
    side: Side,
    price: u64,
}

pub struct OrderBook {
    // Bids: highest price matched first. Reverse<u64> flips BTreeMap's
    // natural ascending order into descending, so `.iter().next()` gives
    // the highest bid.
    bids: BTreeMap<Reverse<u64>, VecDeque<RestingOrder>>,
    // Asks: lowest price matched first — natural ascending order is correct.
    asks: BTreeMap<u64, VecDeque<RestingOrder>>,
    // O(1) cancel lookup.
    locations: HashMap<u64, OrderLocation>,
}

impl OrderBook {
    pub fn new() -> Self {
        OrderBook {
            bids: BTreeMap::new(),
            asks: BTreeMap::new(),
            locations: HashMap::new(),
        }
    }

        /// Submit a new order. Matches immediately against the opposite side
    /// where possible; any unfilled remainder rests in the book.
    /// Returns all trades generated by this order.
    pub fn add_order(&mut self, order_id: u64, side: Side, price: u64, mut qty: u32) -> Vec<Trade> {
        let mut trades = Vec::new();

        match side {
            Side::Buy => {
                // Match against asks with ask_price <= our bid price, cheapest first.
                while qty > 0 {
                    let Some((&best_ask_price, _)) = self.asks.iter().next() else {
                        break;
                    };
                    if best_ask_price > price {
                        break; // best ask too expensive, no more matches possible
                    }
                    qty = Self::match_level(
                        &mut self.asks,
                        &mut self.locations,
                        best_ask_price,
                        best_ask_price,
                        order_id,
                        qty,
                        &mut trades,
                    );
                }
            }
            Side::Sell => {
                while qty > 0 {
                    let Some((&Reverse(best_bid_price), _)) = self.bids.iter().next() else {
                        break;
                    };
                    if best_bid_price < price {
                        break; // best bid too cheap, no more matches possible
                    }
                    qty = Self::match_level(
                        &mut self.bids,
                        &mut self.locations,
                        Reverse(best_bid_price),
                        best_bid_price,
                        order_id,
                        qty,
                        &mut trades,
                    );
                }
            }
        }

        if qty > 0 {
            self.rest(order_id, side, price, qty);
        }

        trades
    }

    /// Drain resting orders at one price level against an incoming order,
    /// generating trades until the level is empty or the incoming qty runs out.
    /// Returns the incoming order's remaining unfilled qty.
    fn match_level<K: Ord + Copy>(
        book_side: &mut BTreeMap<K, VecDeque<RestingOrder>>,
        locations: &mut HashMap<u64, OrderLocation>,
        level_key: K,
        level_price: u64,
        incoming_id: u64,
        mut incoming_qty: u32,
        trades: &mut Vec<Trade>,
    ) -> u32 {
        let level = book_side.get_mut(&level_key).unwrap();
        while incoming_qty > 0 {
            let Some(resting) = level.front_mut() else {
                break;
            };
            let traded_qty = incoming_qty.min(resting.qty);
            trades.push(Trade {
                resting_order_id: resting.order_id,
                incoming_order_id: incoming_id,
                // Real exchanges trade at the resting ("maker") order's price,
                // not the aggressor's — that's what level_price is here.
                price: level_price,
                qty: traded_qty,
            });
            resting.qty -= traded_qty;
            incoming_qty -= traded_qty;
            if resting.qty == 0 {
                locations.remove(&resting.order_id);
                level.pop_front();
            }
        }
        if level.is_empty() {
            book_side.remove(&level_key);
        }
        incoming_qty
    }

    fn rest(&mut self, order_id: u64, side: Side, price: u64, qty: u32) {
        let entry = RestingOrder { order_id, qty };
        match side {
            Side::Buy => self.bids.entry(Reverse(price)).or_default().push_back(entry),
            Side::Sell => self.asks.entry(price).or_default().push_back(entry),
        }
        self.locations.insert(order_id, OrderLocation { side, price });
    }

    /// Cancel a resting order. Returns true if it was found and removed.
    pub fn cancel_order(&mut self, order_id: u64) -> bool {
        let Some(loc) = self.locations.remove(&order_id) else {
            return false;
        };
        match loc.side {
            Side::Buy => {
                if let Some(level) = self.bids.get_mut(&Reverse(loc.price)) {
                    level.retain(|o| o.order_id != order_id);
                    if level.is_empty() {
                        self.bids.remove(&Reverse(loc.price));
                    }
                }
            }
            Side::Sell => {
                if let Some(level) = self.asks.get_mut(&loc.price) {
                    level.retain(|o| o.order_id != order_id);
                    if level.is_empty() {
                        self.asks.remove(&loc.price);
                    }
                }
            }
        }
        true
    }

    pub fn best_bid(&self) -> Option<u64> {
        self.bids.keys().next().map(|Reverse(p)| *p)
    }

    pub fn best_ask(&self) -> Option<u64> {
        self.asks.keys().next().copied()
    }
}

impl Default for OrderBook {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resting_order_when_no_match() {
        let mut book = OrderBook::new();
        let trades = book.add_order(1, Side::Buy, 100, 10);
        assert!(trades.is_empty());
        assert_eq!(book.best_bid(), Some(100));
    }

    #[test]
    fn simple_full_match() {
        let mut book = OrderBook::new();
        book.add_order(1, Side::Sell, 100, 10);
        let trades = book.add_order(2, Side::Buy, 100, 10);
        assert_eq!(trades.len(), 1);
        assert_eq!(trades[0].qty, 10);
        assert_eq!(book.best_ask(), None);
        assert_eq!(book.best_bid(), None);
    }

    #[test]
    fn partial_fill_leaves_remainder_resting() {
        let mut book = OrderBook::new();
        book.add_order(1, Side::Sell, 100, 5);
        let trades = book.add_order(2, Side::Buy, 100, 10);
        assert_eq!(trades.len(), 1);
        assert_eq!(trades[0].qty, 5);
        // 5 leftover buy qty should now rest on the bid side.
        assert_eq!(book.best_bid(), Some(100));
        assert_eq!(book.best_ask(), None);
    }

    #[test]
    fn price_priority_best_price_matched_first() {
        let mut book = OrderBook::new();
        book.add_order(1, Side::Sell, 105, 10);
        book.add_order(2, Side::Sell, 100, 10); // better (cheaper) ask, added second
        let trades = book.add_order(3, Side::Buy, 105, 10);
        assert_eq!(trades.len(), 1);
        assert_eq!(trades[0].resting_order_id, 2); // cheaper ask fills first, despite arriving later
    }

    #[test]
    fn time_priority_within_same_price() {
        let mut book = OrderBook::new();
        book.add_order(1, Side::Sell, 100, 5);
        book.add_order(2, Side::Sell, 100, 5); // same price, later -> behind in queue
        let trades = book.add_order(3, Side::Buy, 100, 5);
        assert_eq!(trades.len(), 1);
        assert_eq!(trades[0].resting_order_id, 1); // FIFO: first order in fills first
    }

    #[test]
    fn cancel_removes_order_from_book() {
        let mut book = OrderBook::new();
        book.add_order(1, Side::Buy, 100, 10);
        assert!(book.cancel_order(1));
        assert_eq!(book.best_bid(), None);
        assert!(!book.cancel_order(1)); // already gone, second cancel should fail
    }

    #[test]
    fn no_match_when_prices_dont_cross() {
        let mut book = OrderBook::new();
        book.add_order(1, Side::Sell, 105, 10);
        let trades = book.add_order(2, Side::Buy, 100, 10);
        assert!(trades.is_empty());
        assert_eq!(book.best_bid(), Some(100));
        assert_eq!(book.best_ask(), Some(105));
    }
}